project_id = "pkjpfrffzewdenvdnouu"

[functions.send-whatsapp]
verify_jwt = false

[functions.whatsapp-reminders]
verify_jwt = false

[functions.identify-medication]
verify_jwt = false

[functions.read-exam]
verify_jwt = false
